### ISSUE TITLE
[bug]: not compatible with yaml files

### ISSUE THREAD

**Issue by BlackHole1** [adelf/idea-php-dotenv-plugin#100]
1\.yaml (no any warning):

```yaml
redis:
  port:

mysql:
  port:
```

rename `1.yaml` to `.env.yaml`

```
redis:
  port:
  ~~~~ Duplicate key 

mysql:
  port:
  ~~~~ Duplicate key 
```

https://user-images.githubusercontent.com/8198408/148712250-c071dd01-1a63-4b20-859a-2cb83a6bc040.mp4
