### ISSUE TITLE
Provide public api for collected enviroment variables

### ISSUE THREAD

**Issue by Haehnchen** [adelf/idea-php-dotenv-plugin#4]
As i want implement enviroment completion and navigation for Symfony plugin https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/910 please provide a stable api so i can reuse the implemention, instead of bulding my own. Simple i just need a completion and navigation api for all and given variables.

```
"%env(DB_PASSWORD)%"
```

```
# app/config/config.yml
doctrine:
    dbal:
        # ...
        password: "%env(DB_PASSWORD)%"
```
